Updated DEVICES path

diff --git a/devices/pkg_limesuite b/devices/pkg_limesuite
--- a/devices/pkg_limesuite
+++ b/devices/pkg_limesuite
@@ -11,13 +11,34 @@
 ### LimeSDR Devices
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
-    install|build|package|remove|purge )
+    remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   $1 : LimeSDR Devices"
+        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : LimeSDR Devices"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;&
 
+    remove|purge )
+        cd $SIGPI_SOURCE/LimeSuite/build-dir
+        sudo make uninstall
+        sudo ldconfig
+        cd $SIGPI_SOURCE
+	    rm -rf $SIGPI_SOURCE/LimeSuite
+        sed -i /limesuite/d $SIGPI_INSTALLED_DEVICES
+	
+	    # Remove Menu icon
+        sudo rm $SIGPI_DESKTOP_ICONS/LimeSuite.png
+        # Remove Desktop links
+        sudo rm $SIGPI_DESKTOP_FILES/LimeSuite.desktop
+        ;;&
+    
     install|build|package )
         ## DEPENDENCIES
         sudo apt-get install -y swig
@@ -49,7 +70,7 @@ case "$1" in
         # Add to Menu
         #xdg-desktop-menu install --novendor --noupdate $DESKTOP_DIRECTORY/SIGpi.directory $DESKTOP_FILES/lime-suite.desktop
 
-        cat $SIGPI_PKGLIST|grep "limesuite" >> $SIGPI_INSTALLED
+        cat $SIGPI_DEVLIST|grep "limesuite" >> $SIGPI_INSTALLED_DEVICES
         ;;&
     
     build|package)
@@ -65,26 +86,12 @@ case "$1" in
 
     build )
         sudo make install
-        cat $SIGPI_PKGLIST|grep "limesuite" >> $SIGPI_INSTALLED
+        cat $SIGPI_DEVLIST|grep "limesuite" >> $SIGPI_INSTALLED_DEVICES
         ;;&
 
     package)
         sudo checkinstall --install=no
         sudo mv *.deb $SIGPI_DEBS
-        ;;&
-
-    remove|purge )
-        cd $SIGPI_SOURCE/LimeSuite/build-dir
-        sudo make uninstall
-        sudo ldconfig
-        cd $SIGPI_SOURCE
-	    rm -rf $SIGPI_SOURCE/LimeSuite
-        sed -i /limesuite/d $SIGPI_INSTALLED
-	
-	    # Remove Menu icon
-        sudo rm $SIGPI_DESKTOP_ICONS/LimeSuite.png
-        # Remove Desktop links
-        sudo rm $SIGPI_DESKTOP_FILES/LimeSuite.desktop
         ;;&
 
     install|build|package|remove|purge )
diff --git a/devices/pkg_plutosdr b/devices/pkg_plutosdr
--- a/devices/pkg_plutosdr
+++ b/devices/pkg_plutosdr
@@ -5,42 +5,24 @@
 ###
 ### pkg_plutosdr
 ###
-### 20260111-2300
+### 20260117-2300
 ###
 
-case "$1" in 
-    remove )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Remove PlutoSDR"
-        echo -e "${SIGPI_BANNER_RESET}"
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
 
+case "$1" in 
+    remove|purge )
         sudo dpkg -r libiio
         sudo dpkg -r SoapyPlutoSDR
-        sed -i /libiio/d $SIGPI_INSTALLED
+        sed -i /libiio/d $SIGPI_INSTALLED_DEVICES
+        ;;&
 
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   PlutoSDR Removed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
-    purge )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Purge PlutoSDR"
-        echo -e "${SIGPI_BANNER_RESET}"
-
-        sudo dpkg -P libiio
-        sudo dpkg -P SoapyPlutoSDR
-        sed -i /libiio/d $SIGPI_INSTALLED
-
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   PlutoSDR Purged"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
     install )
-        # PlutoSDR
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ###   Install PlutoSDR "
-        echo -e "${SIGPI_BANNER_RESET}"
-
         ## DEPENDENCIES
         sudo apt-get install -y libaio-dev libusb-1.0-0-dev 
         sudo apt-get install -y libserialport-dev libavahi-client-dev 
diff --git a/devices/pkg_sdrplay b/devices/pkg_sdrplay
--- a/devices/pkg_sdrplay
+++ b/devices/pkg_sdrplay
@@ -5,17 +5,38 @@
 ###
 ### pkg_sdrplay
 ###
-### 20260110-2300
+### 20260117-2300
 ###
 ###
 ###
+
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
 
 case "$1" in 
-    install )
+    remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Install SDRplay and SoapySDRplay"
+        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : SDRplay"
         echo -e "${SIGPI_BANNER_RESET}"
+        ;;&
 
+    remove|purge )
+	    cd $SIGPI_SOURCE/SDRplay/build/host
+        sudo make uninstall
+        sudo ldconfig
+        cd $SIGPI_SOURCE
+        rm -rf $SIGPI_SOURCE/SDRplay
+        rm -rf $HOME/.config/SDRplay
+        sudo rm -rf $SIGPI_DESKTOP/SDRplay.desktop
+        sudo rm -rf $DESKTOP_FILES/SDRplay.desktop
+        sed -i /SDRplay/d $SIGPI_INSTALLED_DEVICES
+        ;;&
+
+    install )
         cd $SIGPI_SCRIPTS
         sudo cp run_SDRplay.sh /usr/local/bin/run_SDRplay.sh
         sudo chmod 755 /usr/local/bin/run_SDRplay.sh
@@ -52,6 +73,7 @@ case "$1" in
         make -j4
         sudo make install
         sudo ldconfig
+        cat $SIGPI_DEVLIST|grep "sdrplay" >> $SIGPI_INSTALLED_DEVICES
 
         echo " "
         echo "Finished. Current user guide can be found here..."
@@ -61,46 +83,11 @@ case "$1" in
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##   SDRplay Device Installed"
         echo -e "${SIGPI_BANNER_RESET}"
-        ;;
-    remove )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Remove SDRplay"
-        echo -e "${SIGPI_BANNER_RESET}"
-        
-	    cd $SIGPI_SOURCE/SDRplay/build/host
-        sudo make uninstall
-        sudo ldconfig
-        cd $SIGPI_SOURCE
-        rm -rf $SIGPI_SOURCE/SDRplay
-        sed -i /SDRplay/d $SIGPI_INSTALLED
+        ;;&
 
+    remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   SDRplay Removed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
-    purge )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Purge SDRplay"
-        echo -e "${SIGPI_BANNER_RESET}"
-               
-	    cd $SIGPI_SOURCE/SDRplay/build/host
-        sudo make uninstall
-        sudo ldconfig
-        cd $SIGPI_SOURCE
-	    rm -rf $SIGPI_SOURCE/SDRplay
-        sed -i /SDRplay/d $SIGPI_INSTALLED
-
-        rm -rf $HOME/.config/SDRplay
-        sudo rm -rf $SIGPI_DESKTOP/SDRplay.desktop
-        sudo rm -rf $DESKTOP_FILES/SDRplay.desktop
-
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   SDRplay Purged"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
+        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : SDRplay - Completed"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esace
