kerberos sdr update

diff --git a/devices/pkg_kerberos b/devices/pkg_kerberos
--- a/devices/pkg_kerberos
+++ b/devices/pkg_kerberos
@@ -11,51 +11,45 @@
 ### Kerberos SDR
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
-    install )
+    remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Install Kerberos SDR"
+        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : kerberos"
         echo -e "${SIGPI_BANNER_RESET}"
+        ;;&
 
-        ## DEPENDENCIES
-        sudo apt-get install -y python3-pip python3-pyqt4 pyqt4-dev-tools build-essential gfortran libatlas3-base
-        sudo apt-get install -y libatlas-base-dev python3-dev python3-setuptools libffi6 libffi-dev python3-tk pkg-config libfreetype6-dev php7.2-cli
-        sudo apt-get install -y libusb-1.0-0-dev
-        pip3 install numpy
-        pip3 install matplotlib
-        pip3 install scipy
-        pip3 install cairocffi
-        pip3 install pyapril
-        pip3 install pyargus
-        pip3 install pyqtgraph
-        pip3 install peakutils
-        pip3 install bottle
-        pip3 install paste
-
-        # PACKAGE
-        cd $SIGPI_SOURCE
-        git clone https://github.com/rtlsdrblog/rtl-sdr-kerberos
-        cd rtl-sdr-kerberos
-        mkdir build	&& cd build
-        cmake ../ -Wno-dev -DINSTALL_UDEV_RULES=ON
-        make -j4
-        sudo make install
-        sudo cp ../rtl-sdr.rules /etc/udev/rules.d/
+    remove )
+        cd $SIGPI_SOURCE/rtl-sdr-kerberos/build
+        sudo make uninstall
         sudo ldconfig
-        cat $SIGPI_PKGLIST|grep "kerberos" >> $SIGPI_INSTALLED
+        cd $SIGPI_SOURCE
+        rm -rf rtl-sdr-kerberos
+        rm -rf SoapyRTLSDR
+        sed -i /rtl-sdr-kerberos/d $SIGPI_INSTALLED_DEVICES
+        ;;&
 
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Kerberos SDR Installed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
-    build )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Build and Install Kerberos SDR"
-        echo -e "${SIGPI_BANNER_RESET}"
+    purge )
+        cd $SIGPI_SOURCE/rtl-sdr-kerberos/build
+        sudo make uninstall
+        sudo ldconfig
+        cd $SIGPI_SOURCE
+        rm -rf rtl-sdr-kerberos
+        rm -rf SoapyRTLSDR
+        sed -i /rtl-sdr-kerberos/d $SIGPI_INSTALLED_DEVICES
+        ;;&
 
+    install|build|package )
         ## DEPENDENCIES
-        sudo apt-get install -y python3-pip python3-pyqt4 pyqt4-dev-tools build-essential gfortran libatlas3-base \
-        libatlas-base-dev python3-dev python3-setuptools libffi6 libffi-dev python3-tk pkg-config libfreetype6-dev php7.2-cli
+        sudo apt-get install -y python3-pip python3-pyqt5 pyqt5-dev-tools gfortran libatlas3-base
+        sudo apt-get install -y libatlas-base-dev python3-dev python3-setuptools 
+        sudo apt-get install -y libffi-dev python3-tk pkg-config libfreetype6-dev php-cli
         sudo apt-get install -y libusb-1.0-0-dev
         pip3 install numpy
         pip3 install matplotlib
@@ -67,7 +61,24 @@ case "$1" in
         pip3 install peakutils
         pip3 install bottle
         pip3 install paste
+        ;;&
 
+     install )
+        ## PACKAGE
+        cd $SIGPI_PACKAGES        
+        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
+	        cd $SIGPI_DEBS
+	        sudo dpkg -i rtl-sdr-kerberos_current_amd64.deb
+        fi
+
+        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
+	        cd $SIGPI_DEBS
+	        sudo dpkg -i rtl-sdr-kerberos_current_arm64.deb
+        fi
+        cat $SIGPI_PKGLIST|grep "rtl-sdr-kerberos" >> $SIGPI_INSTALLED_DEVICES
+        ;;&
+
+    build )
         # PACKAGE
         cd $SIGPI_SOURCE
         git clone https://github.com/rtlsdrblog/rtl-sdr-kerberos
@@ -76,32 +87,10 @@ case "$1" in
         cmake .. -DINSTALL_UDEV_RULES=ON
         make -j4
         sudo make install
-        cat $SIGPI_PKGLIST|grep "kerberos" >> $SIGPI_INSTALLED
+        cat $SIGPI_PKGLIST|grep "rtl-sdr-kerberos" >> $SIGPI_INSTALLED
+        ;;&
 
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Kerberos SDR Built and Installed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
     package )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Package Kerberos SDR"
-        echo -e "${SIGPI_BANNER_RESET}"
-
-        ## DEPENDENCIES
-        sudo apt-get install -y python3-pip python3-pyqt4 pyqt4-dev-tools build-essential gfortran libatlas3-base
-        sudo apt-get install -y libatlas-base-dev python3-dev python3-setuptools libffi6 libffi-dev python3-tk pkg-config libfreetype6-dev php7.2-cli
-        sudo apt-get install -y libusb-1.0-0-dev
-        pip3 install numpy
-        pip3 install matplotlib
-        pip3 install scipy
-        pip3 install cairocffi
-        pip3 install pyapril
-        pip3 install pyargus
-        pip3 install pyqtgraph
-        pip3 install peakutils
-        pip3 install bottle
-        pip3 install paste
-
         # PACKAGE
         cd $SIGPI_SOURCE
         git clone https://github.com/rtlsdrblog/rtl-sdr-kerberos
@@ -110,45 +99,8 @@ case "$1" in
         cmake .. -DINSTALL_UDEV_RULES=ON
         make -j4
         sudo checkinstall --install=no
+        ;;&
 
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Kerberos SDR Packaged. Package available in $SIG_DEBS"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
-    remove )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Remove Kerberos SDR"
-        echo -e "${SIGPI_BANNER_RESET}"
-        
-        cd $SIGPI_SOURCE/rtl-sdr-kerberos/build
-        sudo make uninstall
-        sudo ldconfig
-        cd $SIGPI_SOURCE
-        rm -rf rtl-sdr-kerberos
-        rm -rf SoapyRTLSDR
-        sed -i /kerberos/d $SIGPI_INSTALLED
-
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Kerberos SDR Removed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
-    purge )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Purge Kerberos SDR"
-        echo -e "${SIGPI_BANNER_RESET}"
-       
-        cd $SIGPI_SOURCE/rtl-sdr-kerberos/build
-        sudo make uninstall
-        sudo ldconfig
-        cd $SIGPI_SOURCE
-        rm -rf rtl-sdr-kerberos
-        rm -rf SoapyRTLSDR
-        sed -i /kerberos/d $SIGPI_INSTALLED
-
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   Kerberos SDR Purged"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
     * )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
