Update pkg_wsjtx

diff --git a/packages/pkg_wsjtx b/packages/pkg_wsjtx
--- a/packages/pkg_wsjtx
+++ b/packages/pkg_wsjtx
@@ -6,82 +6,78 @@
 ### pkg_wsjtx
 ###
 
-###
-### 20211208-1200  Currently default to install to keep script backward compatible
-###
+case "$1" in 
+    remove )
+        echo -e "${SIGPI_BANNER_COLOR}"
+        echo -e "${SIGPI_BANNER_COLOR} ##   Remove WSJT-X"
+        echo -e "${SIGPI_BANNER_RESET}"
 
-# REMOVE
-if [ $1 = "remove" ]; then
-    echo -e "${SIGPI_BANNER_COLOR}"
-    echo -e "${SIGPI_BANNER_COLOR} ##"
-    echo -e "${SIGPI_BANNER_COLOR} ##   Remove WSJT-X"
-    echo -e "${SIGPI_BANNER_COLOR} ##"
-    echo -e "${SIGPI_BANNER_RESET}"
+        sudo dpkg -P wsjtx
 
-    sudo dpkg -P wsjtx
+        echo -e "${SIGPI_BANNER_COLOR}"
+        echo -e "${SIGPI_BANNER_COLOR} ##   WSJT-X Removed"
+        echo -e "${SIGPI_BANNER_RESET}"
+        ;;
+    purge )
+        echo -e "${SIGPI_BANNER_COLOR}"
+        echo -e "${SIGPI_BANNER_COLOR} ##   Purge WSJT-X"
+        echo -e "${SIGPI_BANNER_RESET}"
 
-    echo -e "${SIGPI_BANNER_COLOR}"
-    echo -e "${SIGPI_BANNER_COLOR} ##   WSJT-X Removed"
-    echo -e "${SIGPI_BANNER_RESET}"
-fi
+        sudo dpkg -P wsjtx
+        rm -rf $HOME/.config/WSJT-X.INI
+        sudo rm -rf $SIGPI_DESKTOP/wsjtx.desktop
+        sudo rm -rf $DESKTOP_FILES/wsjtx.desktop
 
-# PURGE
-if [ $1 = "purge" ]; then
-    echo -e "${SIGPI_BANNER_COLOR}"
-    echo -e "${SIGPI_BANNER_COLOR} ##"
-    echo -e "${SIGPI_BANNER_COLOR} ##   Purge WSJT-X"
-    echo -e "${SIGPI_BANNER_COLOR} ##"
-    echo -e "${SIGPI_BANNER_RESET}"
+        echo -e "${SIGPI_BANNER_COLOR}"
+        echo -e "${SIGPI_BANNER_COLOR} ##   WSJT-X Purged"
+        echo -e "${SIGPI_BANNER_RESET}"
+        ;;
+    install )
+        echo -e "${SIGPI_BANNER_COLOR}"
+        echo -e "${SIGPI_BANNER_COLOR} ##"
+        echo -e "${SIGPI_BANNER_COLOR} ##   Install WSJT-X"
+        echo -e "${SIGPI_BANNER_COLOR} ##"
+        echo -e "${SIGPI_BANNER_RESET}"
 
-    sudo dpkg -P wsjtx
-    rm -rf $HOME/.config/WSJT-X.INI
-    sudo rm -rf $SIGPI_DESKTOP/wsjtx.desktop
-    sudo rm -rf $DESKTOP_FILES/wsjtx.desktop
+        ## DEPENDENCIES
+        sudo apt-get install -y gfortran fftw3-dev qtbase5-dev qttools5-dev libqt5serialport5-dev  qtmultimedia5-dev 
+        sudo apt-get install -y libqt5multimedia5-plugins libqt5sql5-sqlite autoconf automake libtool texinfo
+        sudo apt-get install -y libusb-1.0-0-dev libudev-dev libboost-all-dev asciidoctor
 
-    echo -e "${SIGPI_BANNER_COLOR}"
-    echo -e "${SIGPI_BANNER_COLOR} ##   WSJT-X Purged"
-    echo -e "${SIGPI_BANNER_RESET}"
-fi
+        ## PACKAGE
+        cd $SIGPI_SOURCE
+        if [ "$SIGPI_HWARCH" == "x86" ]; then
+            echo -e "${SIGPI_BANNER_COLOR}"
+            echo -e "${SIGPI_BANNER_COLOR} ##   Not available on x86"
+            echo -e "${SIGPI_BANNER_RESET}"
+            exit 1
+        fi
 
-# INSTALL
-echo -e "${SIGPI_BANNER_COLOR}"
-echo -e "${SIGPI_BANNER_COLOR} ##"
-echo -e "${SIGPI_BANNER_COLOR} ##   Install WSJT-X"
-echo -e "${SIGPI_BANNER_COLOR} ##"
-echo -e "${SIGPI_BANNER_RESET}"
+        if [ "$SIGPI_HWARCH" = "x86_64"]; then
+	        cd $HOME/Downloads
+	        wget https://physics.princeton.edu/pulsar/K1JT/wsjtx_2.5.2_amd64.deb -P $HOME/Downloads
+	        sudo dpkg -i wsjtx_2.5.2_amd64.deb
+        fi
 
-## DEPENDENCIES
-sudo apt-get install -y gfortran fftw3-dev qtbase5-dev qttools5-dev libqt5serialport5-dev  qtmultimedia5-dev 
-sudo apt-get install -y libqt5multimedia5-plugins libqt5sql5-sqlite autoconf automake libtool texinfo
-sudo apt-get install -y libusb-1.0-0-dev libudev-dev libboost-all-dev asciidoctor
+        if [ "$SIGPI_HWARCH" = "armhf"]; then
+	        cd $HOME/Downloads
+	        wget https://physics.princeton.edu/pulsar/K1JT/wsjtx_2.5.2_armhf.deb -P $HOME/Downloads
+	        sudo dpkg -i wsjtx_2.5.2_armhf.deb
+        fi
 
-## PACKAGE
-cd $SIGPI_SOURCE
-if [ "$SIGPI_HWARCH" == "x86" ]; then
-    echo -e "${SIGPI_BANNER_COLOR}"
-    echo -e "${SIGPI_BANNER_COLOR} ##   Not available on x86"
-    echo -e "${SIGPI_BANNER_RESET}"
-    exit 1
-fi
+        if [ "$SIGPI_HWARCH" = "aarch64"]; then
+	        cd $HOME/Downloads
+	        wget https://physics.princeton.edu/pulsar/K1JT/wsjtx_2.5.2_amd64.deb -P $HOME/Downloads
+	        sudo dpkg -i wsjtx_2.5.2_amd64.deb
+        fi
 
-if [ "$SIGPI_HWARCH" = "x86_64"]; then
-	cd $HOME/Downloads
-	wget https://physics.princeton.edu/pulsar/K1JT/wsjtx_2.5.2_amd64.deb -P $HOME/Downloads
-	sudo dpkg -i wsjtx_2.5.2_amd64.deb
-fi
-
-if [ "$SIGPI_HWARCH" = "armhf"]; then
-	cd $HOME/Downloads
-	wget https://physics.princeton.edu/pulsar/K1JT/wsjtx_2.5.2_armhf.deb -P $HOME/Downloads
-	sudo dpkg -i wsjtx_2.5.2_armhf.deb
-fi
-
-if [ "$SIGPI_HWARCH" = "aarch64"]; then
-	cd $HOME/Downloads
-	wget https://physics.princeton.edu/pulsar/K1JT/wsjtx_2.5.2_amd64.deb -P $HOME/Downloads
-	sudo dpkg -i wsjtx_2.5.2_amd64.deb
-fi
-
-echo -e "${SIGPI_BANNER_COLOR}"
-echo -e "${SIGPI_BANNER_COLOR} ##   WSJT-X Installed"
-echo -e "${SIGPI_BANNER_RESET}"
+        echo -e "${SIGPI_BANNER_COLOR}"
+        echo -e "${SIGPI_BANNER_COLOR} ##   WSJT-X Installed"
+        echo -e "${SIGPI_BANNER_RESET}"
+        ;;
+    * )
+        echo -e "${SIGPI_BANNER_COLOR}"
+        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
+        echo -e "${SIGPI_BANNER_RESET}"
+        ;;
+esac
