Update case error checking

diff --git a/packages/pkg_aptdec b/packages/pkg_aptdec
--- a/packages/pkg_aptdec
+++ b/packages/pkg_aptdec
@@ -11,12 +11,20 @@
 ### Aptdec is a FOSS program that decodes images transmitted by NOAA weather satellites.
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : APTdec (NOAA APT)"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;&
+
     remove )
         cd $SIGPI_SOURCE/aptdec/build
         sudo make uninstall
@@ -24,6 +32,7 @@ case "$1" in
         rm -rf $SIGPI_SOURCE/aptdec
         sed -i /aptdec/d $SIGPI_INSTALLED
         ;;&
+
     purge )
         cd $SIGPI_SOURCE/aptdec/build
         sudo make uninstall
@@ -33,10 +42,12 @@ case "$1" in
         sudo rm -rf $SIGPI_DESKTOP/aptdec.desktop
         sudo rm -rf $DESKTOP_FILES/aptdec.desktop
         ;;&
+
     install|build|package )
         ## DEPENDENCIES
         sudo apt-get install -y libsndfile-dev libpng-dev
         ;;&    
+
     install )
         ## PACKAGE
         cd $SIGPI_SOURCE
@@ -49,7 +60,7 @@ case "$1" in
         sudo make install
         sudo ldconfig
         cat $SIGPI_PKGLIST|grep "aptdec" >> $SIGPI_INSTALLED 
-
+        
         ## DESKTOP
         # Add Icon
         # Add Desktop
@@ -58,6 +69,7 @@ case "$1" in
         # Add to Menu
         xdg-desktop-menu install --novendor --noupdate $DESKTOP_DIRECTORY/SIGpishell.directory $DESKTOP_FILES/aptdec.desktop
         ;;&
+
     build )
         ## PACKAGE
         cd $SIGPI_SOURCE
@@ -70,7 +82,7 @@ case "$1" in
         sudo make install
         sudo ldconfig
         cat $SIGPI_PKGLIST|grep "aptdec" >> $SIGPI_INSTALLED 
-
+        
         ## DESKTOP
         # Add Icon
         # Add Desktop
@@ -79,6 +91,7 @@ case "$1" in
         # Add to Menu
         xdg-desktop-menu install --novendor --noupdate $DESKTOP_DIRECTORY/SIGpishell.directory $DESKTOP_FILES/aptdec.desktop
         ;;&
+
     package )       
         ## PACKAGE
         git clone --recursive https://github.com/Xerbo/aptdec.git
@@ -96,14 +109,10 @@ case "$1" in
         # Change Category
         # Add to Menu
         ;;&
+
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : APTdec (NOAA APT) - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_ax25 b/packages/pkg_ax25
--- a/packages/pkg_ax25
+++ b/packages/pkg_ax25
@@ -10,6 +10,13 @@
 ### Packet Radio AX.25
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -40,11 +47,6 @@ case "$1" in
     remove|purge|install )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : AX.25 - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_cm256cc b/packages/pkg_cm256cc
--- a/packages/pkg_cm256cc
+++ b/packages/pkg_cm256cc
@@ -16,6 +16,13 @@
 ###    The number of blocks of redundant data (RecoveryCount), which must be no more than 256 - OriginalCount.
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -83,12 +90,6 @@ case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : cm256cc - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_cygnusrfi b/packages/pkg_cygnusrfi
--- a/packages/pkg_cygnusrfi
+++ b/packages/pkg_cygnusrfi
@@ -6,8 +6,16 @@
 ### pkg_cygnusrfi
 ###
 ###
-### 20260112-2300
+### 20260114-2300
 ###
+
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 
 case "$1" in 
     remove|purge|install|build|package )
@@ -71,12 +79,6 @@ case "$1" in
     remove|purge|install )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : CygnusRFI - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-        
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_direwolf b/packages/pkg_direwolf
--- a/packages/pkg_direwolf
+++ b/packages/pkg_direwolf
@@ -11,6 +11,13 @@
 ### DireWolf AFSK APRS TNC
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -81,7 +88,7 @@ case "$1" in
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##   DireWolf Installed"
         echo -e "${SIGPI_BANNER_RESET}"
-        ;;
+        ;;&
     
     build )
         ## PACKAGE
@@ -141,13 +148,7 @@ case "$1" in
 
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : CygnusRFI - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-        
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
+        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : DireWolf (AFSK APRS) - Completed"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_dsdcc b/packages/pkg_dsdcc
--- a/packages/pkg_dsdcc
+++ b/packages/pkg_dsdcc
@@ -12,6 +12,13 @@
 ### and synthesize the decoded speech. Speech synthesis requires mbelib, which is a separate package.
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -81,12 +88,6 @@ case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : DSDcc - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_gnuradio b/packages/pkg_gnuradio
--- a/packages/pkg_gnuradio
+++ b/packages/pkg_gnuradio
@@ -12,6 +12,13 @@
 ### For aarm64 we use previously compiled 3.9.8.0 for now
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -191,12 +198,6 @@ case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : GNUradio - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR}" ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_libdab b/packages/pkg_libdab
--- a/packages/pkg_libdab
+++ b/packages/pkg_libdab
@@ -13,6 +13,13 @@
 ### The library interface is given in dab-api.h
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -102,12 +109,6 @@ case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : LibBTbb - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&    
-       
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_liquid-dsp b/packages/pkg_liquid-dsp
--- a/packages/pkg_liquid-dsp
+++ b/packages/pkg_liquid-dsp
@@ -14,6 +14,13 @@
 ### synchronizers, complex mathematical operations, and much more.
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -81,12 +88,6 @@ case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : Liquid-DSP - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_mbelib b/packages/pkg_mbelib
--- a/packages/pkg_mbelib
+++ b/packages/pkg_mbelib
@@ -12,6 +12,13 @@
 ### ProVoice and the "Half Rate 3600x2250 bit/s vocoder used in various radio systems.
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -80,12 +87,6 @@ case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : mbelib (P25 Phase) - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_nrsc5 b/packages/pkg_nrsc5
--- a/packages/pkg_nrsc5
+++ b/packages/pkg_nrsc5
@@ -12,6 +12,13 @@
 ### a command-line interface as well as an API upon which other applications can be built.
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -84,12 +91,6 @@ case "$1" in
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : NRSC5 (HD Radio) - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_qsstv b/packages/pkg_qsstv
--- a/packages/pkg_qsstv
+++ b/packages/pkg_qsstv
@@ -9,6 +9,12 @@
 ### 20260113-2300
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
 
 case "$1" in 
     remove|purge|install|build|package )
@@ -70,13 +76,7 @@ case "$1" in
     
     remove|purge|install )
         echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : Linpac - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
+        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : QSSTV - Completed"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_rtl_433 b/packages/pkg_rtl_433
--- a/packages/pkg_rtl_433
+++ b/packages/pkg_rtl_433
@@ -11,7 +11,13 @@
 ### RTL_433 - RTL-SDR based 433.92MHz ISM band signal decoder
 ###
 
-case "$1" in
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -94,11 +100,5 @@ case "$1" in
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : rtl_433 - Completed"
         echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
+    ;;
 esac
diff --git a/packages/pkg_serialdv b/packages/pkg_serialdv
--- a/packages/pkg_serialdv
+++ b/packages/pkg_serialdv
@@ -13,6 +13,13 @@
 ### in packet mode over a serial link.
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -41,7 +48,13 @@ case "$1" in
         cd $SIGPI_SOURCE
         git clone https://github.com/f4exb/serialDV.git
         cd serialDV
-        git reset --hard "v1.1.4"
+               ;;&
+
+    * )
+        echo -e "${SIGPI_BANNER_COLOR}"
+        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
+        echo -e "${SIGPI_BANNER_RESET}"
+ git reset --hard "v1.1.4"
         mkdir build; cd build
         cmake -Wno-dev ..
         make -j4
@@ -79,12 +92,6 @@ case "$1" in
      remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : SerialDV - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_urh b/packages/pkg_urh
--- a/packages/pkg_urh
+++ b/packages/pkg_urh
@@ -12,6 +12,13 @@
 ###
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -25,6 +32,7 @@ case "$1" in
         echo -e "${SIGPI_BANNER_COLOR} ##   URH Removed"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
+
     purge )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##   Purge URH"
@@ -37,6 +45,7 @@ case "$1" in
         echo -e "${SIGPI_BANNER_COLOR} ##   URH Purged"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
+
     install )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##"
@@ -70,14 +79,16 @@ case "$1" in
             echo -e "${SIGPI_BANNER_RESET}"
         fi
         ;;
+
     build )
         echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   SIGpi Build option not available"
+        echo -e "${SIGPI_BANNER_COLOR} ##   Build option not available"
         echo -e "${SIGPI_BANNER_RESET}"
-	    ;;
-    * )
+        ;;
+
+    package )
         echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
+        echo -e "${SIGPI_BANNER_COLOR} ##   Package option not available"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_volk b/packages/pkg_volk
--- a/packages/pkg_volk
+++ b/packages/pkg_volk
@@ -9,6 +9,13 @@
 ###  20260113-2300
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -41,16 +48,9 @@ case "$1" in
         sudo mv *.deb $SIGPI_DEBS
         ;;&
     
-    
     remove|purge|install|build|package )
         echo -e "${SIGPI_BANNER_COLOR}"
         echo -e "${SIGPI_BANNER_COLOR} ##  $1 : VOLK - Completed"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;&
-
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR}" ##  ERROR: Unkown action or package"
         echo -e "${SIGPI_BANNER_RESET}"
         ;;
 esac
diff --git a/packages/pkg_wireshark b/packages/pkg_wireshark
--- a/packages/pkg_wireshark
+++ b/packages/pkg_wireshark
@@ -6,6 +6,13 @@
 ### pkg_wireshark
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
+
 case "$1" in 
     remove )
         echo -e "${SIGPI_BANNER_COLOR}"
@@ -78,11 +85,6 @@ case "$1" in
         echo -e "${SIGPI_BANNER_COLOR} ##   SIGpi Build option not available"
         echo -e "${SIGPI_BANNER_RESET}"
 	    ;;
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
 esac
 
 # 20240108-0500
