fix

diff --git a/packages/pkg_dosbox b/packages/pkg_dosbox
--- a/packages/pkg_dosbox
+++ b/packages/pkg_dosbox
@@ -11,6 +11,12 @@
 ### DOSbox package script
 ###
 
+if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
+    echo -e "${SIGPI_BANNER_COLOR}"
+    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
+    echo -e "${SIGPI_BANNER_RESET}"
+    exit 1
+fi
 
 case "$1" in 
     remove )
@@ -52,7 +58,7 @@ case "$1" in
         ## PACKAGE
         cd $SIGPI_SOURCE
         sudo apt-get install -y dosbox
-        cp $SIGPI_SCRIPTS/config_dosbox-TEMPLATE $SIGPI_ETC/sigpi_dosbox.conf
+        cp $SIGPI_HOME/config_dosbox-TEMPLATE $SIGPI_ETC/sigpi_dosbox.conf
         cat $SIGPI_PKGLIST|grep "dosbox" >> $SIGPI_INSTALLED
 
         ## DESKTOP
@@ -70,17 +76,12 @@ case "$1" in
         ;;
     build )
         echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   SIGpi build option not available"
+        echo -e "${SIGPI_BANNER_COLOR} ##   Build option not available"
         echo -e "${SIGPI_BANNER_RESET}"
 	    ;;
-   package )
+    package )
         echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##   SIGpi package option not available"
+        echo -e "${SIGPI_BANNER_COLOR} ##   Package option not available"
         echo -e "${SIGPI_BANNER_RESET}"
 	    ;;
-    * )
-        echo -e "${SIGPI_BANNER_COLOR}"
-        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
-        echo -e "${SIGPI_BANNER_RESET}"
-        ;;
 esac
